raicorp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('users/', include('users.urls')),
    path('', views.index, name="index"),

    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.HomeLanding, name="HomeLanding"),
    # path('<int:pk>/', views.Home, name="todohome"),
    path('', views.Home, name="todohome"),
    path('todoadd/', views.TodoAdd, name="todoadd"),
    path('tododelete/<int:pk>/', views.TodoDelete, name='tododelete'),
    path('todoedit/<int:pk>/', views.TodoEdit, name="todoedit"),
    path('todocomplete/<int:pk>/', views.TodoComplete, name="todocomplete")
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    #including default auth urls
    # path('', include('django.contrib.auth.urls')),

    #login
    path('login/', views.LoginUser, name="login"),

    #logout
    path('logout/', views.LogoutUser, name='logout'),
    #registration page
    path('register/', views.RegisterUser, name="registeruser"),
    path('profiledetails/<str:pk>/', views.ProfileDetails, name="profiledetails"),
]

todo/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.forms.utils import to_current_timezone

# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="todo", null=True)
    title = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    mobile = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return str(self.user)

todo/forms.py
from django.forms import ModelForm
from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        # fields = '__all__'
        fields = ['title']

users/forms.py
from django.forms import fields
from users.models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user','mobile','address']

raicorp/views.py
from django.shortcuts import render
from django.http import HttpResponse
def index(request):
    # return HttpResponse('Welcome to RaiCorp!')
    return render(request, 'index.html')

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from todo.models import Todo

from .forms import TodoForm
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from django.http import HttpResponseRedirect


# Create your views here.
@login_required(login_url='users:login')
def Home(request):
    # return HttpResponse("Welcome to Todo Home Page!")
    # todos = Todo.objects.get(user__id=pk).order_by('-id')
    todos = Todo.objects.filter(user__id=request.user.id).order_by('-created_at')
    context = {
        'todos': todos
    }
    return render(request, 'todohome.html', context)

@login_required(login_url='login')
def TodoAdd(request):
    form = TodoForm(request.POST)
    if request.method == 'POST':
        # form = TodoForm(request.POST, request.FILES, instance=request.user.todo)
        form = TodoForm(request.POST, instance=request.user)
        if form.is_valid():
            title = form.cleaned_data.get('title','')
            Todo.objects.create(title=title, user=request.user)
            print(title)
            form.save()
            messages.success(request, "A todo has been created!")
            # return redirect('todohome')
            # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            # return HttpResponseRedirect('/todo/'+str(request.user.id)+'/')
            response = redirect('todohome')
            return response
        else:
            messages.error(request, "A todo could not be created! Try again.")
            # return HttpResponse("Invalid submission!")
    return render(request, 'todoadd.html', {'form': form})

@login_required(login_url='login')
def TodoDelete(request, pk):
    todo_to_delete = Todo.objects.get(id=pk)
    todo_to_delete.delete()
    return redirect('todohome')

@login_required(login_url='login')
def TodoEdit(request, pk):
    todo_edit = Todo.objects.get(id=pk)
    form = TodoForm(request.POST, instance=todo_edit)
    if form.is_valid():
        form.save()
        return redirect('todohome')
    context = {'form': form}
    return render(request, 'todoadd.html', context)

@login_required(login_url='login')
def TodoComplete(request, pk):
    form = Todo.objects.get(id=pk)
    form.completed = True
    form.save()
    return redirect('todohome')

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.models import 

from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import CreateUserForm, ProfileForm
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from .models import Profile
# Create your views here.

def RegisterUser(request):
    form = CreateUserForm()
    customers = []
    users = User.objects.all()
    for user in users:
        customers.append(user.username)
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been successfully created')
            print('User created')
            return redirect('users:login')
        elif request.POST['username'] in customers:
            print('Same username')
            messages.error(request, 'Oops! Username is already taken. Try with new one.')
        else:
            print('wrong password')
            messages.error(request, 'Oops! something went wrong. Try again.')
    context = {'form': form}
    return render(request, 'registeruser.html', context)

def LoginUser(request):
    # form 
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success (request, f'Logged in successfully. Welcome {request.user}')
            return redirect('index')
        else:
            messages.error(request, 'Enter the valid credentials')
    return render(request, 'login.html')

@login_required(login_url='users:login')
def LogoutUser(request):
    logout(request)
    return redirect('users:login')

def ProfileDetails(request, pk):
    user = User.objects.get(id=pk)
    profile_user = Profile.objects.get(user__id=pk)
    
    context = {
        'user':user,
        'profile_user': profile_user
    }
    # profile = Profile.objects.get(user=user)
    # profile = User.objects.filter(username=user).select_related('Profile')
    return render(request, 'profiledetails.html', context)

templates/_messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" {% endif %}>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
        {% endfor %}
</ul>
{% endif %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    {% block title %}
    {% endblock title %}
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}
    

    <!-- Optional JavaScript; choose one of the two! -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title> RaiCorp | Home </title>
{% endblock title %}

{% block content %}
<div class="container text-center mt-4">
  {% include '_messages.html' %}
  {% if user.is_authenticated %}
  {% else %}
  <div class="row mb-3">
        <div class="col-md-6 d-grid gap-2">
            <a href="{% url 'users:login'%}" class="btn btn-secondary">Sign In</a>
        </div>
        <div class="col-md-6 d-grid gap-2">
            <a href="{% url 'users:registeruser' %}" class="btn btn-primary btn-block">Sign Up</a>
        </div>
    </div>
  {% endif %}
    
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'images/main_slider.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </a>
      </div>


    
    <div id="samaya" class="text-center bg bg-info p-4 mt-3"></div>
</div>
<script>
    var dt = new Date()
    document.getElementById('samaya').innerHTML = dt.toLocaleString();
</script>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block title %}
<title>RaiCorp | Login </title>
{% endblock title %}
{% block content %}
<div class="container mt-4">
{% if form.errors %}
    <p>Your username and password didn't match. Please try again</p>
{% endif %}
<div class="row">
    <div class="col-md-6">
<div class="accordion-body border border-primary rounded">
<form method="post" action="{% url 'users:login' %}" class="mb-3">
    {% csrf_token %}
    {% include '_messages.html' %}
    <h1>Login</h1>
    <div class="form-group">
        <input type="text" name="username" id="username" class="form-control mt-3" placeholder="Enter Username">
    </div>
    <div class="form-group">
        <input type="password" name="password" id="password" class="form-control my-3" placeholder="Enter Password">
        <small class="float-right py-3 showPasswordToggle">SHOW</small>
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
<a href="{% url 'users:registeruser' %}">Not a member?</a>
</div>
</div>
</div>
{% endblock content %}
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">RaiCorp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'todohome' %}">Todo</a>
        </li>
        {% endif %}
      </ul>
      
      <div style="margin-right: 10px;">
        <div class="dropdown">
          <p class="text-light dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Settings</p>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if request.user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:profiledetails' request.user.id %}">Profile</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            {% endif %}
            
          </ul>
        </div>
      </div>
      {% if request.user.is_authenticated %}
      <div class="text-secondary">Welcome, {{request.user}}</div>
      {% endif %}
    </div>
  </div>
</nav>

templates/profiledetails.html
{% extends 'base.html' %}
{% block title %}
<title>User Profile</title>
{% endblock title %}
{% block content %}
<div class="container">
<div class="my-3">
    <h3>{{request.user}}'s Profile</h3>
      <p>Username: {{user.username}}</p>
      <p>First Name: {{user.first_name}}</p>
      <p>Last Name: {{user.last_name}}</p>
      <p>Email: {{user.email}}</p>

      <p>Mobile: {{profile_user.mobile}}</p>
      <p>Address: {{profile_user.address}}</p>
    </div>
</div>
{% endblock content %}

templates/registeruser.html
{% extends 'base.html' %}
{% block title %}
<title> Create User - {{block.super}}</title>
{% endblock title %}
{% block content %}
<div class="container mt-3">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 border border-secondary rounded p-2">
        <h1>Sign Up</h1>
    <form method="post" action="">
      {% include '_messages.html' %}
        {% csrf_token %}
        <hr>
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          {{form.username}}
          <div id="usernameHelp" class="form-text">Username should only contain alpha numeric</div>
          <hr>
        </div>
        <div class="mb-3">
          <label for="email" class="form-label">Email</label>
          {{form.email}}
        </div>
        <hr>
        <div class="mb-3">
          <label for="password1" class="form-label">Password</label>
          {{form.password1}}
        </div>
        <hr>
        <div class="mb-3">
          <label for="password2" class="form-label">Confirm Password</label>
          {{form.password2}}
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      </div>
      <div class="col-md-4"></div>
    </div>
</div>
{% endblock content %}

templates/todoadd.html
{% extends 'base.html' %}
{% block title %}
<title>Todo | Add a todo</title>
{% endblock title %}
{% block content %}
<div class="container my-4">
{% include '_messages.html' %}
    <form action="{% url 'todoadd'%}" method="post">
        {% csrf_token %}
        {{form.title.label}}
        {{form.title}}
        <br>
        {{form.completed.label}}
        {{form.completed}}

        <input type="submit" value="Submit">
    </form>
</div>
{% endblock content %}

templates/tododelete.html
{% extends 'base.html' %}

templates/todohome.html
{% extends 'base.html' %}
{% block title %}
<title>RaiCorp Todo | Home</title>
{% endblock title %}

{% block content %}
<div class="container mt-3">
  {% include '_messages.html' %}
  <a href="{% url 'todoadd'%}" class="m-2 btn btn-primary">Add a todo</a>
  <hr>
  {% if todos.exists %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Tasks</th>
        <th scope="col">Date Created</th>
        <th scope="col">Status</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
      <tr>
        <td scope="row">{{forloop.counter}}</td>
        {% if todo.completed == True %}
        <td><strike>{{todo.title}}</strike></td>
        {% else %}
        <td>{{todo.title}}</td>
        {% endif %}
        
        <td>{{todo.created_at}}</td>
        <td>{{todo.completed}}</td>
        <td>
          <!-- Button trigger modal -->
          <a ahref="#" type="button" class="btn btn-danger" data-bs-toggle="modal"
            data-bs-target="#todoModal">Delete</a>
          {% if  todo.completed == True %}
          <a href="#" class="btn btn-success disabled">Completed</a>
          <a href="#" class="btn btn-info disabled">Edit</a>
          {% else %}
          <a href="{% url 'todoedit' todo.id %}" class="btn btn-info">Edit</a>
          <a href="{% url 'todocomplete' todo.id %}" class="btn btn-success">Complete</a>
          {% endif %}
        </td>
      </tr>
      <!-- Modal -->
      <div class="modal fade" id="todoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title text-danger" id="todoModalLabel">Heads up!</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure to delete {{todo.title}}?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
              <a href="{% url 'tododelete' todo.id %}" class="btn btn-primary">Confirm</a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
      <h3 class="mt-4 text-center">No todos found!</h3>
      <h5 class="text-center">:) </h5>
  {% endif %}
</div>
{% endblock content %}